name: Docker Image CI

on:
  push:
    branches: [ main ]

jobs:

  push:
    name: Push Docker Image
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
    
    - uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
    - name: Log in to Docker Hub
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
    - name: Extract metadata (tags, labels) for Docker
      id: meta
      with:
        images: debuggerboy/uwsgi:2.0.20
    
    - name: Build and push Docker image
    - uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
      with:
        context: .
        push: true
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
