#################################################################################################################################
# Demo Parameterized Actions
#
# Source : https://github.blog/changelog/2020-07-06-github-actions-manual-triggers-with-workflow_dispatch/
# Supported by:
#             - https://stackoverflow.com/questions/62736315/invoke-github-actions-workflow-manually-and-pass-parameters
#################################################################################################################################

name: Create a Tag and Release

on: 
  workflow_dispatch:
    inputs:
      tagString:
        description: 'Choose A Tag (must be unique)'     
        required: true
      tagCreator:
        description: 'Enter your name'     
        required: true
      tagDescription:
        description: 'Describe This Release'
        default: 'New Build'
        
jobs:
  tag_and_release:
    name: Create a tag and release
    runs-on: ubuntu-latest
    
    steps:      
      - name: Check output
        run: |
          echo "Tag String: ${{ github.event.inputs.tagString }}"
          echo "Tag Author: ${{ github.event.inputs.tagCreator }}"
            echo "Tag Description: ${{ github.event.inputs.tagDescription }}"
